import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { GameMode } from '@/app/(protected)/(game)/models/GameMode'
import { GameStatus } from '@/app/(protected)/(game)/models/GameStatus'
import { Map } from '@/app/(protected)/(game)/models/Map'

/**
 * A game of any mode. The columns are the ones every mode shares (and the
 * ones that are filtered or indexed); everything particular to the mode —
 * rounds, answers, guesses, clocks — lives in `data`, which only the engine of
 * the mode reads and writes (see services/gameModes.ts). The players are in
 * `game_players` (GamePlayer).
 */
@Entity({ table: 'games' })
export class Game extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  mode!: GameMode

  @Column({ cast: 'number' })
  mapId!: number | null

  @Column({ cast: 'number' })
  status!: GameStatus

  /** Invitation code of multiplayer games (null for single player games and once the game ends). */
  @Column()
  code!: string | null

  @Column({ cast: 'number' })
  hostUserId!: number | null

  /**
   * Increased on every write. Updates are conditional on it (optimistic
   * locking: several players may act at the same time) and clients poll with
   * it to know whether something changed.
   */
  @Column({ cast: 'number' })
  version!: number

  /** State of the game mode. Never sent to the browser as is (see GameModeEngine.toView). */
  @Column({ cast: 'json' })
  data!: unknown

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  startedAt!: Date | null

  @Column({ cast: 'date' })
  finishedAt!: Date | null

  @Column({ cast: 'date' })
  updatedAt!: Date

  @BelongsTo(() => Map, 'mapId')
  map?: Map
}
