import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { GameMode } from '@/app/(protected)/(game)/models/GameMode'
import { GameStatus } from '@/app/(protected)/(game)/models/GameStatus'

/**
 * A game played by a user. Only its progress and final score are stored: the
 * rounds themselves (images, answers, guesses) live in the encrypted game
 * token the player keeps (see services/gameTokens.ts).
 */
@Entity({ table: 'games' })
export class Game extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  userId!: number

  @Column({ cast: 'number' })
  mode!: GameMode

  @Column({ cast: 'number' })
  status!: GameStatus

  @Column({ cast: 'number' })
  roundsCount!: number

  /**
   * Rounds already guessed. A token is only accepted when it carries exactly
   * this many guessed rounds, so an old token can't be replayed to re-guess.
   */
  @Column({ cast: 'number' })
  playedRounds!: number

  @Column({ cast: 'number' })
  totalScore!: number

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  finishedAt!: Date | null
}
