import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { GameStatus } from '@/app/(protected)/(game)/models/GameStatus'
import { Quest } from '@/app/(protected)/(game)/models/Quest'

/**
 * A game played by a user. Only its progress and final score are stored: the
 * rounds themselves (images, answers, guesses) live in the encrypted game
 * token the player keeps (see services/gameTokens.ts).
 */
@Entity({ table: 'games' })
export class Game extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  userId!: number

  @Column({ cast: 'number' })
  questId!: number

  @Column({ cast: 'number' })
  status!: GameStatus

  @Column({ cast: 'number' })
  roundsCount!: number

  /**
   * Rounds already guessed. A token is only accepted when it carries exactly
   * this many guessed rounds, so an old token can't be replayed to re-guess.
   */
  @Column({ cast: 'number' })
  playedRounds!: number

  @Column({ cast: 'number' })
  totalScore!: number

  /**
   * When the current round was shown to the player (timed quests only). The
   * time limit is measured from here, server side. Reset after every guess.
   */
  @Column({ cast: 'date' })
  roundStartedAt!: Date | null

  @Column({ cast: 'date' })
  createdAt!: Date

  @Column({ cast: 'date' })
  finishedAt!: Date | null

  @BelongsTo(() => Quest, 'questId')
  quest?: Quest
}
