import { BaseEntity, BelongsTo, Column, Entity } from '@neogroup/neorm'
import { Place } from '@/app/(protected)/(game)/models/Place'

/** One round of a game: the image shown, its real position and the player's guess. */
@Entity({ table: 'game_rounds' })
export class GameRound extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  gameId!: number

  /** 1-based position of the round inside the game. */
  @Column({ cast: 'number' })
  roundNumber!: number

  @Column({ cast: 'number' })
  placeId!: number

  @Column()
  imageId!: string

  @Column({ cast: 'number' })
  latitude!: number

  @Column({ cast: 'number' })
  longitude!: number

  @Column({ cast: 'number' })
  guessLatitude!: number | null

  @Column({ cast: 'number' })
  guessLongitude!: number | null

  @Column({ cast: 'number' })
  distanceMeters!: number | null

  @Column({ cast: 'number' })
  score!: number | null

  @Column({ cast: 'date' })
  guessedAt!: Date | null

  @BelongsTo(() => Place, 'placeId')
  place?: Place
}
