import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { MapSettings } from '@/app/(protected)/(game)/models/MapSettings'

/**
 * A map of the game (e.g. "Ciudades del mundo"): where to play, chosen after
 * the game mode — the places their locations are drawn from (`map_places`).
 * The rules (rounds, time limit...) belong to the game mode, not to the map.
 */
@Entity({ table: 'maps' })
export class Map extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  description!: string

  /** Image of the map card: a path under /public or an absolute URL. */
  @Column()
  image!: string | null

  /** Settings that override the ones of the game modes (see MapSettings). Null: none. */
  @Column({ cast: 'json' })
  settings!: MapSettings | null

  @Column({ cast: 'boolean' })
  enabled!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
