import { BaseEntity, Column, Entity } from '@neogroup/neorm'

/**
 * Fallback cache of the Street View panoramas already found inside a place.
 * Only read when live searches can't fill a game (see services/locations.ts).
 */
@Entity({ table: 'place_locations' })
export class PlaceLocation extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  placeId!: number

  /** Google Street View panorama id. */
  @Column()
  panoId!: string

  @Column({ cast: 'number' })
  latitude!: number

  @Column({ cast: 'number' })
  longitude!: number

  @Column({ cast: 'date' })
  createdAt!: Date
}
