import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { GameMode } from '@/app/(protected)/(game)/models/GameMode'
import { PolygonGeometry } from '@/app/(protected)/(game)/models/PlaceArea'

/**
 * A playable area of a game mode (e.g. a city in "Ciudades del mundo"). The
 * area is either a circle (`latitude`/`longitude` + `radiusMeters`) or a
 * GeoJSON polygon; the game draws random street-level locations inside it.
 */
@Entity({ table: 'places' })
export class Place extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  /** ISO 3166-1 alpha-2 country code. */
  @Column()
  countryCode!: string

  @Column({ cast: 'number' })
  mode!: GameMode

  @Column({ cast: 'number' })
  latitude!: number

  @Column({ cast: 'number' })
  longitude!: number

  /** Circle radius in meters. Null when the area is described by `polygon`. */
  @Column({ cast: 'number' })
  radiusMeters!: number | null

  /** GeoJSON polygon of the area. Null for circles. */
  @Column({ cast: 'json' })
  polygon!: PolygonGeometry | null

  @Column({ cast: 'boolean' })
  enabled!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
