import { BaseEntity, Column, Entity } from '@neogroup/neorm'

/**
 * Cache of the street-level images already found inside a place. Every image
 * the location finder discovers is stored here, so a place whose live search
 * fails (no coverage around the random points, provider down, rate limits)
 * can still be played from previously found locations.
 */
@Entity({ table: 'place_locations' })
export class PlaceLocation extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column({ cast: 'number' })
  placeId!: number

  /** Id of the image in the imagery provider (Mapillary image key). */
  @Column()
  imageId!: string

  @Column({ cast: 'number' })
  latitude!: number

  @Column({ cast: 'number' })
  longitude!: number

  @Column({ cast: 'boolean' })
  isPano!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
