import { BaseEntity, Column, Entity } from '@neogroup/neorm'
import { GameMode } from '@/app/(protected)/(game)/models/GameMode'
import { PlaceGeometry } from '@/app/(protected)/(game)/models/PlaceGeometry'

/**
 * A playable area of a game mode (e.g. a city in "Ciudades del mundo"). Its
 * `geometry` (GeoJSON: a circle or a polygon, see PlaceGeometry) is the area
 * the game draws random street-level locations from.
 */
@Entity({ table: 'places' })
export class Place extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  /** ISO 3166-1 alpha-2 country code. */
  @Column()
  countryCode!: string

  @Column({ cast: 'number' })
  mode!: GameMode

  /** Area of the place as a GeoJSON geometry (circle or polygon). */
  @Column({ cast: 'json' })
  geometry!: PlaceGeometry

  @Column({ cast: 'boolean' })
  enabled!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
