import { BaseEntity, Column, Entity } from '@neogroup/neorm'

/**
 * A game mode of the main menu (e.g. "Ciudades del mundo"): how many rounds
 * its games have, the time limit of each round and the places its rounds are
 * drawn from (the `quest_place` table).
 */
@Entity({ table: 'quests' })
export class Quest extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  description!: string

  /** Rounds of every game of the quest. */
  @Column({ cast: 'number' })
  rounds!: number

  /** Time limit of each round, in seconds. Null = no time limit. */
  @Column({ cast: 'number' })
  time!: number | null

  /** Image of the quest card in the main menu: a path under /public or an absolute URL. */
  @Column()
  image!: string | null

  @Column({ cast: 'boolean' })
  enabled!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
