import { BaseEntity, Column, Entity } from '@neogroup/neorm'

/**
 * A quest of the main menu (e.g. "Ciudades del mundo"): the content of the
 * games — the places their locations are drawn from (`quest_places`). The
 * rules (rounds, time limit...) belong to the game modes the quest offers
 * (`quest_modes`).
 */
@Entity({ table: 'quests' })
export class Quest extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  name!: string

  @Column()
  description!: string

  /** Image of the quest card in the main menu: a path under /public or an absolute URL. */
  @Column()
  image!: string | null

  @Column({ cast: 'boolean' })
  enabled!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date
}
