import { BaseEntity, Column, Entity, Serializable } from '@neogroup/neorm'
import { getUserDisplayName } from '@/app/utils/users'

/** A GeoQuests player. Signs in with Google or with email + password (verified by email). */
@Entity({ table: 'users' })
export class User extends BaseEntity {
  @Column({ primaryKey: true, autoGenerated: true })
  id!: number

  @Column()
  email!: string

  /** Null for accounts created through Google (they never set a password). */
  @Column()
  passwordHash!: string | null

  /** Player name shown in the game (HUD, summaries). */
  @Column()
  name!: string | null

  /** True when the user verified their email address. Always true for Google-authenticated users. */
  @Column({ cast: 'boolean' })
  emailVerified!: boolean

  /** False disables the account's login. */
  @Column({ cast: 'boolean' })
  active!: boolean

  @Column({ cast: 'date' })
  createdAt!: Date

  @Serializable()
  get displayName(): string {
    return getUserDisplayName(this)
  }
}
